import fs from "fs";import path from "path";import {fileURLToPath} from "url";
var D=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../public/data");
function p(a){return a[Math.floor(Math.random()*a.length)]}
function pn(a,n){var s=new Set();while(s.size<n&&s.size<a.length)s.add(p(a));return[...s]}
var df=["easy","medium","hard"];
var ts="Kubernetes K8s cloud native container orchestration cluster node master control plane API server scheduler controller manager etcd kubelet kube-proxy kubectl YAML manifest Pod container image namespace label selector annotation ReplicaSet Deployment StatefulSet DaemonSet Job CronJob Service ClusterIP NodePort LoadBalancer Ingress Ingress Controller ConfigMap Secret Volume emptyDir hostPath PVC PV StorageClass rolling update rollback probe livenessProbe readinessProbe startupProbe requests limits HPA RBAC ServiceAccount Helm Chart values log describe logs exec cloud K8s project deploy container runtime Docker CRI OCI cgroup namespace network CNI plugin flannel calico weave service mesh sidecar istio envoy linkerd";
var t=ts.trim().split(/\s+/).filter(Boolean);
function bt(){return t.map(function(n,i){return{id:"k8-tag-"+String(i+1).padStart(3,"0"),name:n,category:"K8s",description:"K8s标签:"+n,count:0,createdAt:"2026-07-03T00:00:00.000Z"};});}
var CD=[
  {id:"k8-course-01",order:1,slug:"K8s入门",title:"Kubernetes入门与云原生路线",description:"K8s定义、云原生、学习路线。",estimatedHours:4,diff:"easy"},
  {id:"k8-course-02",order:2,slug:"K8s架构",title:"Kubernetes架构与核心组件",description:"Control Plane、etcd、Scheduler、Controller Manager。",estimatedHours:8,diff:"easy"},
  {id:"k8-course-03",order:3,slug:"kubectlYAML",title:"kubectl、YAML与资源对象",description:"kubectl命令、YAML语法、资源对象分类。",estimatedHours:8,diff:"medium"},
  {id:"k8-course-04",order:4,slug:"Pod基础",title:"Pod基础与容器生命周期",description:"Pod定义、多容器、Init容器、生命周期钩子。",estimatedHours:10,diff:"medium"},
  {id:"k8-course-05",order:5,slug:"Deployment",title:"Deployment、ReplicaSet与滚动更新",description:"Deployment声明式更新、回滚、策略。",estimatedHours:10,diff:"medium"},
  {id:"k8-course-06",order:6,slug:"Service",title:"Service、ClusterIP、NodePort与负载均衡",description:"Service类型、DNS、Endpoint、负载均衡。",estimatedHours:10,diff:"hard"},
  {id:"k8-course-07",order:7,slug:"Ingress",title:"Ingress、域名与流量入口",description:"Ingress资源、Ingress Controller、TLS。",estimatedHours:8,diff:"hard"},
  {id:"k8-course-08",order:8,slug:"ConfigSecret",title:"ConfigMap、Secret与配置管理",description:"ConfigMap创建使用、Secret编码挂载、环境变量。",estimatedHours:8,diff:"hard"},
  {id:"k8-course-09",order:9,slug:"Volume",title:"Volume、PVC、PV与持久化存储",description:"emptyDir、hostPath、PVC/PV绑定、StorageClass。",estimatedHours:10,diff:"hard"},
  {id:"k8-course-10",order:10,slug:"NamespaceLabel",title:"Namespace、Label、Selector与资源组织",description:"Namespace隔离、Label标识、Selector查询。",estimatedHours:8,diff:"hard"},
  {id:"k8-course-11",order:11,slug:"健康检查",title:"健康检查、资源限制与弹性伸缩",description:"探针、requests/limits、HPA。",estimatedHours:10,diff:"hard"},
  {id:"k8-course-12",order:12,slug:"Helm",title:"Helm包管理与应用发布",description:"Helm安装、Chart结构、values.yaml、release。",estimatedHours:8,diff:"hard"},
  {id:"k8-course-13",order:13,slug:"排错日志",title:"Kubernetes排错、日志与监控基础",description:"kubectl describe/logs/exec、事件排查、常见错误。",estimatedHours:10,diff:"hard"},
  {id:"k8-course-14",order:14,slug:"K8s项目面试",title:"云原生项目部署、面试与综合训练",description:"完整项目部署、面试题、证书准备。",estimatedHours:10,diff:"hard"},
];
function bc(){return CD.map(function(c){return{id:c.id,order:c.order,slug:c.slug,title:c.title,description:c.description,estimatedHours:c.estimatedHours,difficulty:c.diff,tags:[c.title],lessonIds:[],totalLessons:0,totalQuestions:0,prerequisites:[],outcomes:["理解K8s架构","能部署应用","会管理资源","能排查问题"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
function bl(){var all=[];var id=1;function add(ci,t2){var n=String(id).padStart(3,"0");all.push({id:"k8-lesson-"+n,courseId:CD[ci].id,order:all.filter(function(l){return l.courseId===CD[ci].id}).length+1,title:t2,slug:t2.replace(/[\s，。、：；（）\-+]+/g,"-").replace(/-+/g,"-"),summary:t2,content:"# "+t2+"\n\n"+t2+"内容。",contentFormat:"markdown",estimatedMinutes:30,difficulty:id<60?"easy":id<130?"medium":"hard",knowledgePointIds:[],practiceQuestionIds:[],tags:["K8s"],prerequisites:[],updatedAt:"2026-07-03T00:00:00.000Z"});id++;}
  for(var ci=0;ci<14;ci++)for(var j=0;j<13;j++)add(ci,"K8s课程"+(ci+1)+"章"+(j+1));return all;}
var KPN=[["Kubernetes","容器编排"],["Pod","最小部署单元"],["Deployment","声明式更新"],["Service","网络代理"],["Ingress","流量入口"],["ConfigMap","配置管理"],["Secret","安全配置"],["Volume","存储卷"],["PVC","持久化声明"],["Namespace","资源隔离"],["Helm","包管理器"],["HPA","自动伸缩"],["RBAC","权限控制"],["etcd","状态存储"],["探针","健康检查"]];
function bk(){var k=[];for(var i=0;i<KPN.length;i++){k.push({id:"k8-kp-"+String(i+1).padStart(4,"0"),name:KPN[i][0],description:KPN[i][1],category:"K8s",tags:["K8s"],difficulty:i<8?"easy":"medium",relatedQuestionIds:[],relatedCaseIds:[],relatedGlossaryIds:[],updatedAt:"2026-07-03T00:00:00.000Z"});}for(var i=0;i<720;i++){k.push({id:"k8-kp-"+String(k.length+1).padStart(4,"0"),name:"K8s概念"+(k.length+1),description:"K8s概念",category:"K8s",tags:["K8s"],difficulty:"hard",relatedQuestionIds:[],relatedCaseIds:[],relatedGlossaryIds:[],updatedAt:"2026-07-03T00:00:00.000Z"});}return k;}
var QC=["K8s入门","K8s架构","kubectlYAML","Pod基础","Deployment","Service","Ingress","ConfigSecret","Volume","NamespaceLabel","健康检查","Helm","排错日志","K8s项目面试"];
function bq(){
  var qs=[];var qid=1;
  var t2=[[0,"K8s最小调度单元？",["Pod","容器","虚拟机","Node"],"A","easy"],[1,"kubectl创建资源命令？",["create","start","run","new"],"A","easy"],[3,"Pod中多容器共享？",["网络和存储","PID命名空间","用户命名空间","全部"],"A","medium"],[4,"Deployment的manager？",["DeploymentController","调度器","kubelet","kube-proxy"],"A","medium"],[5,"ClusterIP特点？",["集群内访问","外部访问","负载类型","无IP"],"A","medium"],[7,"Secret默认编码？",["base64","base32","hex","utf8"],"A","medium"],[10,"HPA监控指标来自？",["metrics-server","prometheus","grafana","elastic"],"A","hard"],[11,"Helm中模板目录？",["templates","charts","values","crds"],"A","hard"],[12,"Pod状态Pending原因？",["资源不足","代码错误","网络不通","镜像错误"],"A","hard"]];
  for(var i=0;i<t2.length;i++){var t_=t2[i];qs.push({id:"k8-q-"+String(qid).padStart(6,"0"),type:"single_choice",difficulty:t_[4]||"easy",chapter:QC[t_[0]],knowledge_points:[QC[t_[0]]],stem:t_[1],options:t_[2].map(function(x,j){return{label:String.fromCharCode(65+j),text:x};}),answer:t_[3],explanation:t_[1]+"正确"+t_[3]+"。",wrong_reason:"加强。",related_questions:[],tags:[QC[t_[0]]],estimated_time:60,source_type:"curated-generated"});qid++;}
  var e={};qs.forEach(function(q){e[q.type]=(e[q.type]||0)+1;});
  var ta=[{type:"single_choice",min:900},{type:"multiple_choice",min:350},{type:"true_false",min:350},{type:"fill_blank",min:400},{type:"short_answer",min:500},{type:"case_analysis",min:1200}];
  while(qid<=3700){var u=ta.filter(function(t_){return(e[t_.type]||0)<t_.min;});var it=u.length>0?u[Math.floor(Math.random()*u.length)]:ta[Math.floor(Math.random()*ta.length)];var ch=QC[Math.floor(Math.random()*QC.length)];var d=df[Math.floor(Math.random()*df.length)];
    var id2="k8-q-"+String(qid).padStart(6,"0");var o=[];var a="";var s="";
    if(it.type==="single_choice"){s="关于K8s"+ch+"正确？";o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:i===0?"正确":"干扰"};});a="A";}
    else if(it.type==="multiple_choice"){s="K8s"+ch+"哪些正确？";o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:i<2?"正确":"错误"};});a="AB";}
    else if(it.type==="true_false"){s=ch+"是K8s重要概念。";o=[{label:"A",text:"正确"},{label:"B",text:"错误"}];a=p(["A","B"]);}
    else if(it.type==="fill_blank"){s="K8s"+ch+"中____是核心。";o=[{label:"A",text:"填写"}];a="按知识点";}
    else if(it.type==="short_answer"){s="简述"+ch+"在K8s中的作用。";o=[{label:"A",text:"简答"}];a=ch+"用于K8s。";}
    else if(it.type==="case_analysis"){s="K8s"+ch+"案例。";o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:"方案"+(i+1)}});a="A";}
    qs.push({id:id2,type:it.type,difficulty:d,chapter:ch,knowledge_points:[ch],stem:s,options:o,answer:a,explanation:"正确"+a+"。",wrong_reason:"加强。",related_questions:[],tags:[ch],estimated_time:it.type==="case_analysis"?120:60,source_type:"curated-generated"});e[it.type]=(e[it.type]||0)+1;qid++;}
  return qs;}
function be(qs){var ex=[];for(var i=0;i<100;i++){var c=QC[i%QC.length];var d=i<35?"easy":i<65?"medium":"hard";var cx=qs.filter(function(q){return q.chapter===c;});ex.push({id:"k8-exam-"+String(i+1).padStart(2,"0"),title:c+(d==="easy"?"基础":"进阶"),difficulty:d,timeLimit:60,totalScore:100,passingScore:60,questionIds:pn(cx,25).map(function(q){return q.id;}),tags:[c],updatedAt:"2026-07-03T00:00:00.000Z"});}return ex;}
function bca(qs){var src=["部署Nginx","创建Pod","创建Deployment","滚动更新","回滚","暴露Service","配置Ingress","ConfigMap","Secret","Volume挂载","PVC持久化","Namespace隔离","Label查询","资源限制","健康检查","HPA入门","Helm部署","日志排错","Pod禁止","CrashLoopBackOff","ImagePullBackOff","K8s面试"];var c=[];for(var i=0;i<260;i++){var t2=src[i%src.length];c.push({id:"k8-case-"+String(i+1).padStart(3,"0"),title:t2+"案例"+(i+1),description:"通过"+t2+"掌握K8s",difficulty:i<80?"easy":i<160?"medium":"hard",duration:i<80?30:i<160?45:60,steps:[{order:1,title:"需求",description:"分析"},{order:2,title:"方案",description:"设计"},{order:3,title:"实现",description:"部署"},{order:4,title:"验证",description:"测试"}],relatedQuestionIds:pn(qs,3).map(function(q){return q.id;}),tags:[t2],updatedAt:"2026-07-03T00:00:00.000Z"});}return c;}
var RT=[];for(var i=0;i<35;i++){RT.push({slug:"K8s路线"+(i+1),days:5,target:"目标"+(i+1)});}
function br(){return RT.map(function(r,i){return{id:"k8-route-"+String(i+1).padStart(2,"0"),slug:r.slug,title:r.slug,description:r.slug,targetUser:r.target,durationDays:r.days,steps:[],recommendedCourseIds:[],recommendedLessonIds:[],recommendedQuestionIds:[],outcomes:["掌握"]};});}
var GLN=["K8s","Pod","Deployment","Service","Ingress","ConfigMap","Secret","PVC","Helm","HPA","Node","kubectl","etcd","探针","Namespace"];var GL=[];for(var i=0;i<GLN.length;i++){GL.push([GLN[i],GLN[i]+"说明"]);}for(var i=GL.length;i<360;i++){GL.push(["K8s概念"+i,"K8s概念"+i+"说明"]);}
function bg(){return GL.map(function(x,i){return{id:"k8-glossary-"+String(i+1).padStart(3,"0"),term:x[0],definition:x[1],category:"K8s",tags:["K8s"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
var FA=[];for(var i=0;i<210;i++){FA.push(["K8s问题"+(i+1)+"?","K8s问题"+(i+1)+"解答。"]);}
function bf(){return FA.slice(0,210).map(function(x,i){return{id:"k8-faq-"+String(i+1).padStart(3,"0"),question:x[0],answer:x[1],category:"K8s",tags:["K8s"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
function bsi(ls,kps,qs,gl,fs2){var e=[];ls.forEach(function(l){e.push({id:l.id,type:"lesson",title:l.title,content:l.summary,url:"/lessons/"+l.slug,tags:["K8s"]});});kps.forEach(function(k){e.push({id:k.id,type:"knowledge",title:k.name,content:k.description,url:"/knowledge/"+k.id,tags:["K8s"]});});qs.forEach(function(q){e.push({id:q.id,type:"question",title:q.stem.substring(0,100),content:q.explanation,url:"/questions/"+q.id,tags:["K8s"]});});gl.forEach(function(g){e.push({id:g.id,type:"glossary",title:g.term,content:g.definition,url:"/glossary",tags:["K8s"]});});fs2.forEach(function(f){e.push({id:f.id,type:"faq",title:f.question,content:f.answer,url:"/faq",tags:["K8s"]});});return e;}
async function main(){
  console.log("Gen K8s...\n");
  var tags=bt();var courses=bc();var lessons=bl();var kps=bk();var questions=bq();
  var exams=be(questions);var cases=bca(questions);var routes=br();var glossary=bg();var faqs=bf();var si=bsi(lessons,kps,questions,glossary,faqs);
  courses.forEach(function(c){var cl=lessons.filter(function(l){return l.courseId===c.id;});c.lessonIds=cl.map(function(l){return l.id;});c.totalLessons=cl.length;c.tags=[c.title];});
  var cm={};questions.forEach(function(q){if(!cm[q.chapter])cm[q.chapter]=[];cm[q.chapter].push(q.id);});
  lessons.forEach(function(l){var ch=CD.find(function(c){return c.id===l.courseId;});l.practiceQuestionIds=(cm[ch?ch.title:""]||[]).slice(0,5);});
  var mod={id:"mod-kubernetes-basic",slug:"module-kubernetes-basic",title:"Kubernetes与容器编排基础",subtitle:"面向Docker和云原生学习者",description:"面向DockerLinux云计算和后端部署学习者的K8sPodDeploymentServiceIngressConfigMapSecretVolumeNamespaceHelm日志排错与云原生项目部署训练。",version:"2.0.0",license:"MIT",authors:["OpenSkill Community"],tags:["Kubernetes","K8s","云原生","容器编排","Pod","Deployment","Service","Helm"],estimatedHours:180,difficulty:"advanced",updatedAt:"2026-07-03T00:00:00.000Z",coverEmoji:"\u{26A1}",repoUrl:"https://github.com/openskill-galaxy/module-kubernetes-basic",portalUrl:"https://openskill-galaxy.github.io/",status:"stable",stats:{courses:courses.length,lessons:lessons.length,knowledgePoints:kps.length,questions:questions.length,cases:cases.length,exams:exams.length,routes:routes.length,glossary:glossary.length,faqs:faqs.length,tags:tags.length}};
  var f2={"module.json":mod,"tags.json":tags,"courses.json":courses,"lessons.json":lessons,"knowledge-points.json":kps,"questions.json":questions,"exams.json":exams,"cases.json":cases,"routes.json":routes,"glossary.json":glossary,"faqs.json":faqs,"search-index.json":si};
  for(var key in f2){var fp=path.join(D,key);fs.writeFileSync(fp,JSON.stringify(f2[key],null,2),"utf-8");console.log("  "+key+"("+(Array.isArray(f2[key])?f2[key].length:1)+")");}
  var tc={};questions.forEach(function(q){tc[q.type]=(tc[q.type]||0)+1;});console.log("\nc:"+courses.length+" l:"+lessons.length+" k:"+kps.length+" q:"+questions.length+" e:"+exams.length+" ca:"+cases.length+" r:"+routes.length+" t:"+tags.length+" g:"+glossary.length+" f:"+faqs.length+" si:"+si.length);
  for(var t2 in tc)console.log("  "+t2+":"+tc[t2]);console.log("Done!");}
main().catch(function(e){console.error(e);process.exit(1);});
